#!/bin/bash
#
# fiemap-test
#
# Verifies the fiemap output received on stdin specifies the same data as the
# contents of the file named as its argument. ("make test" runs this script.)
#
# TODO: Replace this bash script with a better awk -f script.

set -ef

die() {
    printf '%s: error: %s\n' "$0" "$1" >&2
    exit 1
}

(($# >= 1)) || die 'too few arguments'
(($# <= 1)) || die 'too many arguments'
readonly path="$1"

# FIXME: Replace this with the actual test implementation.
# This code serves merely to process all input, to test the Makefile.
[ -e "$path" ] || die "$path: not found"
sed 's/.*/[&]/'
