#!/usr/bin/env bash
#
# fiemap-test-backend
#
# This script performs the verification portion fiemap-test. You should run
# ./fiemap-test instead of running this script directly.
#
# TODO: Replace this bash script with a better awk -f script.

set -f
echo "$EUID"
