#!/bin/bash
#
# fiemap-test
#
# Runs fiemap on a file, and reconstitutes the file based on the locations and
# sizes of the physical blocks provided by fiemap. Running fiemap need not
# typically be done as root, but reading data directly from a block device does
# require root privileges. Only that part of the job is elevated; sudo is used.

set -ef
set -o pipefail
./fiemap "$@" | tee >(sudo ./fiemap-test-backend "$@")
