#!/bin/sh
#
# is-clang - check if a compiler command seems to be for a Clang compiler
#
# This file is part of extents, tools for querying and accessing file extents.
#
# Written in 2019 by Eliah Kagan <degeneracypressure@gmail.com>.
#
# To the extent possible under law, the author(s) have dedicated all copyright
# and related and neighboring rights to this software to the public domain
# worldwide. This software is distributed without any warranty.
#
# You should have received a copy of the CC0 Public Domain Dedication along
# with this software. If not, see
# <http://creativecommons.org/publicdomain/zero/1.0/>.

if [ "$#" -ne 1 ]; then
    printf 'Usage:  %s NAME\n' "$0"
    exit 1
fi

if printf '%s' "$1" | grep -qE '^clang(-|$)'; then
    echo yes
else
    echo no
fi
